# Generated by Django 5.1.1 on 2024-09-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
